project:
  type: book

book:
  title: "Santa Teresa"
  author: "Andre Ferrari"
  date: "10/11/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - api_santa_teresa.qmd
    - dados_santa_teresa.qmd
    - summary.qmd
    - pessoal.qmd
    - compras.qmd
    - orcamento.qmd

    

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

